### ISSUE TITLE
As a developer of a machine learning system, I want to upload images to the server so that they are added to my data set on my user page.

### ISSUE THREAD

**Issue by seanjone** [UB-CSE/course-project-a3-image-server#2]
Acceptance Test:
1. Upload image using drop box on home page.
2. Select the 'Upload Image' button
3. Select the Hamburger menu
4. Go to user page link
5. Verify uploaded image is shown as a part of data for user

**Comment by louismot** [comment]
User stories should always be aimed towards the user, never a developer.
