### ISSUE TITLE
Find library to let you edit photos that you upload to server and resave them. 

### ISSUE THREAD

**Issue by Nick-Anzalone** [UB-CSE/course-project-a3-image-server#36]
Task Test: Write functions with the library and verify that those functions work properly. Pass image in test function and verify that the image is edited the way you wanted it to be.

**Comment by louismot** [comment]
Task tests are needed for this task

**Comment by Nick-Anzalone** [comment]
Task test: Write functions with the library and verify that those functions work properly. Pass image in test function and verify that the image is edited the way you wanted it to be.

**Comment by Nick-Anzalone** [comment]
Pillow Python library was found and I wrote functions using this library, however it has come to my attention that the python library is not supported on the cheshire server, so I will be looking for a PHP library instead.
