### ISSUE TITLE
Write validation tests for login system

### ISSUE THREAD

**Issue by seanjone** [UB-CSE/course-project-a3-image-server#49]

**Comment by Nick-Anzalone** [comment]
Step 1: Visit home page of site
Step 2: visit create account page by clicking on dropdown menu in top left.
step 3: create an account.
step 4: attempt to log into account
step5: verify log in is sucessful. If login is sucessful you will be displayed a welcome page.
step 6: visit home page by going to drop down menu and clicking home.
step 7: verify you are still logged in by seeing your username in the top left corner
