### ISSUE TITLE
As a colleague of a machine learning developer using the image server, I want to request a download of the data set so that I can also receive a local copy of the data set.

### ISSUE THREAD

**Issue by seanjone** [UB-CSE/course-project-a3-image-server#5]
Task Test:
Step 1: Log into site
Step 2: Upload 1 or more images
Step 3: On user page, add data to 1 or more of your images.
Step 4: On the bottom of the user page click on the Download Data Button.
Step 5: Verify that data.csv has the correct data you added to each image along with all images you have uploaded to the server.

**Comment by louismot** [comment]
User stories should always be aimed towards the user, never a developer. It is also vague; what is the data you are requesting? If an end user will not be able to use this functionality, then this may not be a user story.
