### ISSUE TITLE
Adding a new YouTube link to Home page

### ISSUE THREAD

**Issue by mohitgokul** [UB-CSE/course-project-a3-image-server#60]
1. Click on the YouTube link to see how to go through our Project if you're not familiar with how to use it.
2. This will help you in guiding through our project like creating an account and uploading images and to check the weather

https://www.youtube.com/watch?v=cHFAyg065H8&feature=emb_logo&ab_channel=hitbottles

**Comment by louismot** [comment]
1) List the features

2) Make the proper task test(s) for each feature

3) Make sure you link this to as a dependency
