### ISSUE TITLE
As a person with a nature photo, I want to upload an image to the server so that I have an option to download a copy of my image with some cool filters applied to my image

### ISSUE THREAD

**Issue by seanjone** [UB-CSE/course-project-a3-image-server#7]
Acceptance Test:
Step 1: Log in to your account on site. If you do not have an account, log in and create an account. 
Step 2: Upload image on homepage of site.
Step 3: Scroll down to where it says "click here to edit your photos".
Step 4 : Click that button
Step 5:Choose a filter by clicking on one of the buttons that appears with various filters.
Step 6: Verify that an image is downloaded and it is your image with a filter over it.

**Comment by louismot** [comment]
This needs to be rewritten in the form "As a type of user, I want to..... , so that......."
