### ISSUE TITLE
As a person with an astronomy photo, I want to upload the image to the server and enter the metadata information and get information about the weather and temperature levels are displayed.

### ISSUE THREAD

**Issue by seanjone** [UB-CSE/course-project-a3-image-server#8]
Acceptance test:

1. Take a photo and upload it to the server and record the temperature and other weather details.
2. Enter the information about the image using the add_meta button
2. Make sure the weather details that you recorded matches the displayed weather details.

**Comment by ProfMatthewHz** [comment]
This feature does not exist; why is it closed? We are not able to "record the temperature and other weather details."
